//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsLetterAppMVC
{
    public partial class SignupVm
    {
        public int Id { get; set; }
        public string EmailAddress { get; internal set; }
        public string LastName { get; internal set; }
        public string FirstName { get; internal set; }
    }
}